@props([
    'src' => '',
    'alt' => '',
    'sizes' => '100vw',
    'widths' => [480, 768, 1080, 1440],
])
@php
    // Build a srcset from any width variants that exist on disk (generated by
    // `php artisan images:webp`). The web server swaps each .jpg/.png entry for
    // its .webp automatically (public/.htaccess), so we only list the originals.
    $srcset = [];
    if ($src && preg_match('/\.(jpe?g|png)$/i', $src)) {
        foreach ((array) $widths as $w) {
            $variantUrl = preg_replace('/(\.(?:jpe?g|png))$/i', "-{$w}\$1", $src);
            $path = parse_url($variantUrl, PHP_URL_PATH);
            if ($path && is_file(public_path(ltrim(urldecode($path), '/')))) {
                $srcset[] = $variantUrl.' '.$w.'w';
            }
        }
    }
@endphp
<img src="{{ $src }}" alt="{{ $alt }}"
     @if ($srcset) srcset="{{ implode(', ', $srcset) }}" sizes="{{ $sizes }}" @endif
     {{ $attributes }}>
